# Generated by Django 3.2.12 on 2022-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(db_index=True, max_length=10)),
                ('owner_address', models.CharField(max_length=50)),
                ('verified_operators', models.IntegerField()),
                ('verified_operators_av_performance', models.FloatField()),
                ('validators_managed_by_verified_operators', models.IntegerField()),
                ('non_verified_operators', models.IntegerField()),
                ('non_verified_operator_avg_performance', models.FloatField()),
                ('validators_managed_by_non_verified_operators', models.IntegerField()),
                ('validators', models.IntegerField()),
                ('ssv_amount', models.FloatField()),
                ('reward_validators', models.IntegerField()),
                ('reward_validators_with_ssv', models.FloatField()),
                ('reward_verified_operator', models.FloatField()),
                ('reward_all_operator', models.FloatField()),
                ('total_rewards', models.FloatField()),
            ],
        ),
    ]
