# Generated by Django 3.2.12 on 2022-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='reward_validators',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('owner_address', 'round')},
        ),
    ]
