# Generated by Django 3.2.12 on 2022-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0002_auto_20220301_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.TextField()),
                ('dir_name', models.CharField(max_length=100, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
