# Generated by Django 3.1 on 2021-03-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.FloatField()),
            ],
        ),
    ]
